// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tests22297.Models;

#nullable disable

namespace tests22297.Migrations
{
    [DbContext(typeof(ContextMy))]
    partial class ContextMyModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("tests22297.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAction"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("tests22297.Models.FireFighter", b =>
                {
                    b.Property<int>("IdFireFighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFireFighter"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdFireFighter");

                    b.ToTable("FireFighters");
                });

            modelBuilder.Entity("tests22297.Models.FireFighterAction", b =>
                {
                    b.Property<int>("IdFireFighterAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFireFighterAction"), 1L, 1);

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireFighter")
                        .HasColumnType("int");

                    b.HasKey("IdFireFighterAction");

                    b.HasIndex("IdAction");

                    b.HasIndex("IdFireFighter");

                    b.ToTable("FireFightersActions");
                });

            modelBuilder.Entity("tests22297.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFireTruck"), 1L, 1);

                    b.Property<string>("OperationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFireTruck");

                    b.ToTable("FireTrucks");
                });

            modelBuilder.Entity("tests22297.Models.FireTruckAction", b =>
                {
                    b.Property<int>("IdFireTruckAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFireTruckAction"), 1L, 1);

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.HasKey("IdFireTruckAction");

                    b.HasIndex("IdAction");

                    b.HasIndex("IdFireTruck");

                    b.ToTable("FireTruckActions");
                });

            modelBuilder.Entity("tests22297.Models.FireFighterAction", b =>
                {
                    b.HasOne("tests22297.Models.Action", "IdActionNavigation")
                        .WithMany("FireFighterActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tests22297.Models.FireFighter", "IdFireFighterNavigation")
                        .WithMany("FireFighterActions")
                        .HasForeignKey("IdFireFighter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdActionNavigation");

                    b.Navigation("IdFireFighterNavigation");
                });

            modelBuilder.Entity("tests22297.Models.FireTruckAction", b =>
                {
                    b.HasOne("tests22297.Models.Action", "IdActionNavigation")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tests22297.Models.FireTruck", "IdFireTruckNavigation")
                        .WithMany("TruckActions")
                        .HasForeignKey("IdFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdActionNavigation");

                    b.Navigation("IdFireTruckNavigation");
                });

            modelBuilder.Entity("tests22297.Models.Action", b =>
                {
                    b.Navigation("FireFighterActions");

                    b.Navigation("FireTruckActions");
                });

            modelBuilder.Entity("tests22297.Models.FireFighter", b =>
                {
                    b.Navigation("FireFighterActions");
                });

            modelBuilder.Entity("tests22297.Models.FireTruck", b =>
                {
                    b.Navigation("TruckActions");
                });
#pragma warning restore 612, 618
        }
    }
}
